export const GET_ALL_PERSONS = "GET_ALL_PERSONS";
export const GET_PERSONS_LOAD = "GET_PERSONS_LOAD";
export const GET_PERSONS_FAIL = "GET_PERSONS_FAIL";
export const GET_ONE_PERSON = "GET_ONE_PERSON";
